# deploy/k8s/prometheus/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: intelliops-demo
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: demo-app
        static_configs:
          - targets: ["demo-app.intelliops-demo:8080"]
            labels:
              service: demo-app
      - job_name: meridian-gateway
        static_configs:
          - targets: ["meridian-gateway.intelliops-demo:8000"]
            labels:
              service: meridian-gateway
      - job_name: meridian-validation
        static_configs:
          - targets: ["meridian-validation.intelliops-demo:8000"]
            labels:
              service: meridian-validation
      - job_name: meridian-aggregation
        static_configs:
          - targets: ["meridian-aggregation.intelliops-demo:8000"]
            labels:
              service: meridian-aggregation
      - job_name: meridian-reporting
        static_configs:
          - targets: ["meridian-reporting.intelliops-demo:8000"]
            labels:
              service: meridian-reporting
